# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and yarn.lock files
COPY frontend/package*.json .

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY frontend/ .

# Expose the frontend port
EXPOSE 3000

# Serve the frontend on port 3000
CMD ["npm", "run", "dev", "--", "--host"]
