/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountLineChart: typeof import('./components/AccountLineChart.vue')['default']
    AccountTypeToggle: typeof import('./components/AccountTypeToggle.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BalanceSparkline: typeof import('./components/BalanceSparkline.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InterpolateToggle: typeof import('./components/InterpolateToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackedBarChart: typeof import('./components/StackedBarChart.vue')['default']
    TimescaleToggle: typeof import('./components/TimescaleToggle.vue')['default']
    TotalBalanceLineChart: typeof import('./components/TotalBalanceLineChart.vue')['default']
    WealthPieChart: typeof import('./components/WealthPieChart.vue')['default']
  }
}
